// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlYDObbCxQB1hgBJCxwZqdW5stcTcDn1g',
    appId: '1:48671377662:web:0317e16410157d459ebdaf',
    messagingSenderId: '48671377662',
    projectId: 'kaos-chattie',
    authDomain: 'kaos-chattie.firebaseapp.com',
    storageBucket: 'kaos-chattie.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY2SOLb7eRQy_OIr5V9QFRKW_g8dvqEOo',
    appId: '1:48671377662:android:fc6f5bc63b39b0f89ebdaf',
    messagingSenderId: '48671377662',
    projectId: 'kaos-chattie',
    storageBucket: 'kaos-chattie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ysku_x8WvF0YNgRGEygdikewvSvKF4w',
    appId: '1:48671377662:ios:ecf3d38101790a169ebdaf',
    messagingSenderId: '48671377662',
    projectId: 'kaos-chattie',
    storageBucket: 'kaos-chattie.appspot.com',
    iosClientId: '48671377662-f3e8frni4jdnd6393o2td8i74t5sftkb.apps.googleusercontent.com',
    iosBundleId: 'dev.kaosmpd.chattie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6ysku_x8WvF0YNgRGEygdikewvSvKF4w',
    appId: '1:48671377662:ios:ecf3d38101790a169ebdaf',
    messagingSenderId: '48671377662',
    projectId: 'kaos-chattie',
    storageBucket: 'kaos-chattie.appspot.com',
    iosClientId: '48671377662-f3e8frni4jdnd6393o2td8i74t5sftkb.apps.googleusercontent.com',
    iosBundleId: 'dev.kaosmpd.chattie',
  );
}
